site_name: Ricci Flow 讨论班
theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
